version: '3.8'

services:
  # Laravel (PHP)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: centra-backend-app
    container_name: centra-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - centra-network

  # Nginx (Backend + Frontend)
  web:
    image: nginx:alpine
    container_name: centra-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      # Backend
      - ./:/var/www

      # Frontend
      - /var/www/centra/centra-frontend:/var/www/html/frontend

      # Nginx configuration
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

    networks:
      - centra-network

  # MySQL
  db:
    image: mysql:8.0
    container_name: centra-db
    restart: unless-stopped
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - centra-db-data:/var/lib/mysql
    networks:
      - centra-network

  # Redis
  redis:
    image: redis:alpine
    container_name: centra-redis
    restart: unless-stopped
    networks:
      - centra-network

networks:
  centra-network:
    driver: bridge

volumes:
  centra-db-data:
    driver: local