server {
    listen 80;
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    # ==========================================================
    # 1. FRONTEND (Vite / React / Vue)
    # Serve the Frontend in the root "/"
    # ==========================================================
    location / {
        root /var/www/html/frontend;
        try_files $uri $uri/ /index.html;
        gzip_static on;
    }

    # ==========================================================
    # 2. BACKEND (Laravel API & Admin)
    # ==========================================================
    
    # If your Laravel routes start with /api or /admin, 
    # Nginx will process them here:
    location /api {
        root /var/www/public;
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP processor (Your original optimized config)
    location ~ \.php$ {
        root /var/www/public; # Importante: Laravel vive en /public
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # We use "centra-app" because it's the name in your docker-compose
        fastcgi_pass centra-app:9000; 
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Static files of the frontend (Cache)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf)$ {
        root /var/www/html/frontend;
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }
}